/**
 * Rebuild client.js from the sources in assets/.
 *
 * The client bundle must be fully self-contained (the client-modules host
 * serves only /plugins/<id>/client.js), so the wallpaper and the settings
 * corner image are inlined as base64 data URIs.
 *
 * Usage:  node build.mjs   (after editing assets/nachoneko.css or the images)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(join(root, p), "utf8");
const image = (p) => readFileSync(join(root, p)).toString("base64");

let css = read("assets/nachoneko.css");
css = css.replaceAll(
  'url("/nachoneko-bg.jpg")',
  `url("data:image/jpeg;base64,${image("assets/nachoneko-bg.jpg")}")`,
);
css = css.replaceAll(
  'url("/nachoneko-corner.png")',
  `url("data:image/png;base64,${image("assets/nachoneko-corner.png")}")`,
);

const client = `/* Auto-generated by build.mjs — edit assets/nachoneko.css and run \`node build.mjs\`. */
window.__ModuleLoader__.load({
  id: "dsh-nachoneko-theme",
  factory: (require) => {
    const css = ${JSON.stringify(css)};
    const tagId = "dsh-nachoneko-theme/theme.css";
    function apply() {
      if (typeof document !== "undefined" && document.querySelector("style[data-plugin-css=" + JSON.stringify(tagId) + "]") === null) {
        const tag = document.createElement("style");
        tag.dataset.plugin = "dsh-nachoneko-theme";
        tag.dataset.pluginCss = tagId;
        tag.textContent = css;
        document.head.appendChild(tag);
      }
    }
    return { name: "dsh-nachoneko-theme", apply };
  }
});
`;

writeFileSync(join(root, "client.js"), client);
console.log(`client.js written (${client.length} bytes)`);
